fix: remove debug (#12)
<!--
To streamline the process of creating and reviewing pull requests, we
have created a template.
It is not required to follow this template perfectly, but we encourage
you to think about each header.
Before you publish a pull request think about the definition of done for
the issue you are trying to resolve.
-->

<!--
Provide the key for the Jira issue this PR resolves.
-->

Closes PM-

<!--
Provide a concise description on the feature/fix your pull request
implements.
-->

<!--
Provide a list of important changes.

e.g.
* Added tests
* Renamed variable
* Added topic
-->

<!-- Provide additional information necessary for testing this PR. This
includes details like branches in other repos, launch arguments or gait
directories. In the case of a bug fix, provide the steps to reproduce
the bug.-->

<!-- Reviews are automatically requested after the pull request has been
created. Only request for a review if you want a specific person to
review your changes.-->

diff --git a/app/backup-mariadb b/app/backup-mariadb
--- a/app/backup-mariadb
+++ b/app/backup-mariadb
@@ -36,8 +36,12 @@ fi
 # extract secret name
 SECRET_NAME=$(echo "${POD_YAML}" | yq '.items[0].spec.template.spec.containers[0].env[] | select(.name == "MARIADB_ROOT_PASSWORD") | .valueFrom.secretKeyRef.name')
 if [ -z "$SECRET_NAME" ]; then
-  echo "ERROR: No secret found for '${INSTANCE_NAME}' in namespace '$NAMESPACE' - searching for an env var named 'MARIADB_ROOT_PASSWORD'" >&2
-  exit 1
+  # alternatevly, find the volume: name 'mariadb-credentials'
+  SECRET_NAME=$(echo "${POD_YAML}" | yq '.items[0].spec.template.spec.volumes[] | select(.name == "mariadb-credentials") | .secret.secretName')
+  if [ -z "$SECRET_NAME" ]; then
+    echo "ERROR: No secret found for '${INSTANCE_NAME}' in namespace '$NAMESPACE' - searching for an env var named 'MARIADB_ROOT_PASSWORD' or a volume named 'mariadb-credentials'" >&2
+    exit 1
+  fi
 fi
 
 MYSQL_PASSWORD=$(kubectl --context="${KUBECONTEXT}" get secrets -n "$NAMESPACE" "$SECRET_NAME" -o jsonpath='{.data.mariadb-root-password}' | base64 -d)
