fix: enhance secret retrieval logic in backup-mariadb script

diff --git a/app/backup-mariadb b/app/backup-mariadb
--- a/app/backup-mariadb
+++ b/app/backup-mariadb
@@ -22,6 +22,19 @@ if [ -z "$INSTANCE_NAME" ] || [ -z "$NAMESPACE" ]; then
   exit 1
 fi
 
+##
+##
+# │   labels:                                                                                                                                                       │
+# │     app.kubernetes.io/component: primary                                                                                                                        │
+# │     app.kubernetes.io/instance: timelimit                                                                                                                       │
+# │     app.kubernetes.io/managed-by: Helm                                                                                                                          │
+# │     app.kubernetes.io/name: mariadb                                                                                                                             │
+# │     app.kubernetes.io/part-of: mariadb                                                                                                                          │
+# │     app.kubernetes.io/version: 11.4.5                                                                                                                           │
+# │     helm.sh/chart: mariadb-20.4.1                                                                                                                               │
+# │     helm.toolkit.fluxcd.io/name: timelimit                                                                                                                      │
+# │     helm.toolkit.fluxcd.io/namespace: timelimit
+
 FILTER="app.kubernetes.io/name=mariadb,app.kubernetes.io/instance=${INSTANCE_NAME},app.kubernetes.io/component=primary"
 
 POD_YAML=$(kubectl get statefulset -n "$NAMESPACE" -l "$FILTER" -o json)
@@ -36,8 +49,12 @@ fi
 # extract secret name
 SECRET_NAME=$(echo "${POD_YAML}" | yq '.items[0].spec.template.spec.containers[0].env[] | select(.name == "MARIADB_ROOT_PASSWORD") | .valueFrom.secretKeyRef.name')
 if [ -z "$SECRET_NAME" ]; then
-  echo "ERROR: No secret found for '${INSTANCE_NAME}' in namespace '$NAMESPACE' - searching for an env var named 'MARIADB_ROOT_PASSWORD'" >&2
-  exit 1
+  # alternatevly, find the volume: name 'mariadb-credentials'
+  SECRET_NAME=$(echo "${POD_YAML}" | yq '.items[0].spec.template.spec.volumes[] | select(.name == "mariadb-credentials") | .secret.secretName')
+  if [ -z "$SECRET_NAME" ]; then
+    echo "ERROR: No secret found for '${INSTANCE_NAME}' in namespace '$NAMESPACE' - searching for an env var named 'MARIADB_ROOT_PASSWORD' or a volume named 'mariadb-credentials'" >&2
+    exit 1
+  fi
 fi
 
 MYSQL_PASSWORD=$(kubectl --context="${KUBECONTEXT}" get secrets -n "$NAMESPACE" "$SECRET_NAME" -o jsonpath='{.data.mariadb-root-password}' | base64 -d)
